### ISSUE TITLE
Samenwerking

### ISSUE THREAD

**Issue by JuulvanBracht** [stipmonster/api-for-magister-gepro-osi-roosters#18]
Hallo Stipmonster, 
Ik ben bezig met een IOS design. Zou je willen helpen met de recreation van Magister.
Vooral het PHP gedeelte want ik kan het design.

- Juul

**Comment by tkon99** [comment]
Hi Juul,

Stipmonster is niet meer actief bezig met deze library. Zoals ik je eerder zei kun je terecht bij de mijne en kun je daar een issue aanmaken mocht je vragen hebben.

Greoten,
Thomas

**Comment by stipmonster** [comment]
idd wat tkon99 meld.

**Comment by tkon99** [comment]
Off-topic: stipmonster, zou jij mijn pull-request willen accepteren? Dan kunnen we dit soort vragen voortaan vermijden.
